PROMPT:
  - KEY: "JIRA-TASK"
    LABEL: "Jira task ID"
    DEFAULT_VALUE: "{{BRANCH_NAME}}"
  - KEY: "CHANGE"
    LABEL: "Type of change"
    OPTIONS:
      - VALUE: "feat"
        DESC: "A new feature"
      - VALUE: "fix"
        DESC: "A bug fix"
      - VALUE: "test"
        DESC: "Adding missing tests or correcting wrong ones"
      - VALUE: "refactor"
        DESC: "Code changes but no new feature"
      - VALUE: "build"
        DESC: "Changes that affect the build system and/or CI configuration files and scripts"
      - VALUE: "docs"
        DESC: "Documentation only changes"
      - VALUE: "revert"
        DESC: "Rollback code changes"
  - KEY: "BREAKING"
    LABEL: "Breaking change"
    OPTIONS:
      - VALUE: "!"
        DESC: "Contains breaking changes"
      - VALUE: ""
        DESC: "Does not contain breaking changes"
  - KEY: "MESSAGE"
    LABEL: "Commit message"
TEMPLATE: "{{JIRA-TASK}} {{CHANGE}}{{BREAKING}}: {{MESSAGE}}"
