name: PR Style Check

on:
  pull_request:
    branches:
      - main
    types:
      - edited
      - opened
      - reopened
      - synchronize

jobs:
  pr-style-check:
    name: Title and Commit messages format
    runs-on: ubuntu-latest
    env:
      commit_message_format_regex: '^[A-Z]+-[0-9]+\s(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}!?\:\s\w.*'
    steps:
      - name: Check Pull Request title
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: ${{ env.commit_message_format_regex }}
          error: 'PR title must follow the commit message format standard.'
          excludeDescription: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Pull Request commit messages
        if: always()
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: ${{ env.commit_message_format_regex }}
          error: 'PR commit messages must follow the commit message format standard.'
          excludeDescription: 'true'
          excludeTitle: 'true'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}
