name: PR Lint

on:
  pull_request:
    branches:
      - main
    types: [opened, edited, reopened]

jobs:
  pr-lint:
    if: github.actor != 'renovate[bot]'
    runs-on: [self-hosted, simple]
    steps:
      - uses: morrisoncole/pr-lint-action@v1.5.0
        with:
          title-regex: '^([A-Z]+-[0-9]+) ((build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}!?)\:\s([A-Za-z0-9].*)'
          on-failed-regex-fail-action: true
          on-failed-regex-request-changes: true
          on-failed-regex-create-review: true
          on-failed-regex-comment: |
            PR title does not match with regex: `%regex%`

            `(jira task) [change type](! if breaking change): [message]`

            :white_check_mark:
              - OPS-101 chore: Something awesome
              - OPS-101 chore!: Something awesome
              - LEN-101 feat: AAAAAAA

            :x:
              - something awesome
              - chore: Something awesome
              - OPS-101 random: Something awesome
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
